### ISSUE TITLE
interactiveImage not a function

### ISSUE THREAD

**Issue by tmlmt** [jpchateau/Interactive-Image#1]
Hi JP,

First of all, that's a nice plugin you wrote.

However, I am having issues using your script along with other jQuery plugins. The main error I have is "$(...).interactiveImage is not a function" when I load interactive-image.js in the <body> section after the inclusion of jquery itself. It seems that interactive-image is not written as a jQuery plugin i.e. `(function($){})(jQuery);` 

Could you help me with this issue?

**Comment by AmadeusW** [comment]
I have the same issue

**Comment by kazak1377** [comment]
have same problem. What to do? File included.

**Comment by jpchateau** [comment]
Thank you guys for your comments!
Well, I am going to rethink the way the modules are loaded to avoid this kind of conflicts. Perhaps webpack will be used.

**Comment by m3t4l1c** [comment]
+1

**Comment by jpchateau** [comment]
I am closing this issue as a new version is released. Webpack now generates the final js file. You can also take a look at the lib directory to see how the plugin is included in a sample project.
