### ISSUE TITLE
Not able to set the Custom css 

### ISSUE THREAD

**Issue by Navya-adft** [jpchateau/Interactive-Image#10]
i am using Interactive-Image  for my angular project, not able to set some functions ,

- [ ] custom css is not working
       
![image](https://user-images.githubusercontent.com/32817841/94095276-f71f8480-fe53-11ea-8d21-a839214b5c83.png)
![image](https://user-images.githubusercontent.com/32817841/94095292-00105600-fe54-11ea-8cd9-dccc6168ca83.png)

- [ ] How to include zoom functions 

- [ ] how to push new values to the items array
![image](https://user-images.githubusercontent.com/32817841/94095354-26ce8c80-fe54-11ea-971d-03434e94922c.png)
 i try this options ,the items array showing the push values but its not adding new marker

**Comment by jpchateau** [comment]
Hello @Navya-adft !
Thank you for having reported those issues with a good explanation :)

Regarding the custom CSS class, I think this can be related to css rules priority.
Try to add `.interactive-image` before `.my-custom-css-class` in your css file, and check that your own css is loaded after the interactive-image provided css.

```
.interactive-image .my-custom-css-class {
  background-color: blue;
  color: yellow;
}
```

About the new values pushed to the items array, please check the js syntax (last bracket and parenthesis of the object).
If it still does not work, enable the debug mode and check for messages in the console.

**Comment by jpchateau** [comment]
I think it actually works as expected, nethertheless I will update the documentation to make it more clear.
Please reopen this issue or open another one if the problem still persists!
