### ISSUE TITLE
Strange behavior - Image goes after text

### ISSUE THREAD

**Issue by Onore** [jpchateau/Interactive-Image#3]
Hi!

It is not a bug.
But for me it is a logical bug.

**Text**

1. Title
2. Text / Description
3. Image
4. Link

----
1. It is very not typical that image goes after text.

2. Feature request add support HTML in text fields like text, description, etc.

**Comment by jpchateau** [comment]
Hi @Onore !
First of all, thank you for your feedback.

Indeed, it would be better that the text/description goes after the image. So expect to see this in the next release!
Concerning HTML support in text fields, I think giving too much control could lead to bad rendering. I may have to rethink that part, or see what could be possible to do to allow rich texts.

**Comment by jpchateau** [comment]
I close the issue as the strange behavior mentioned is corrected in the [2.4.0](https://github.com/jpchateau/Interactive-Image/tree/v2.4.0) version.
I take the point about the HTML support. I let you open another issue if you want to discuss this feature!
