### ISSUE TITLE
Icomoon font path

### ISSUE THREAD

**Issue by BaztianZH** [jpchateau/Interactive-Image#5]
Hello @jpchateau. Thanks sharing this great plugin.

I'm trying to use it on a symfony project with webpack.
i used yarn to install interactiveimagejs

When i run the dev-server i have this error :

```
error  in ./node_modules/interactiveimagejs/src/scss/main.scss

Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve './fonts/icomoon.svg' in '/var/www/deko/node_modules/interactiveimagejs/src/scss'
```

In src/scss/helpers/_variables.scss file, i found : 

`$icomoon-font-path: '../fonts' !default;`

It seems it should be '../../fonts' to reach src/fonts folder

Or maybe i'm doing something wrong ?

**Comment by jpchateau** [comment]
Hi @BaztianZH!
Thx you for playing with the plugin! I am so sorry for the delay, did you find a workaround?
I did not get the time to test it in a symfony/webpack context yet. Do you use Webpack Encore?
I started a side project to test the plugin in diverse contexts (https://github.com/jpchateau/interactive-image-tester) and I would be glad to integrate a symfony workaround if needed.

**Comment by jpchateau** [comment]
Hello,
I did not manage to reproduce the problem you had using a fresh install of Symfony 5.1.2 with Webpack Encore. But I made a small guide to use the Interactive Image plugin with Symfony. Here it is : https://github.com/jpchateau/interactive-image-tester/blob/master/frameworks/Symfony.md.
I close the issue but if you have more info you can open a new one.
Thank you!
