### ISSUE TITLE
Possibility for "reinit"

### ISSUE THREAD

**Issue by theDyingMountain** [jpchateau/Interactive-Image#6]
Hi @jpchateau,
thx for your great plugin. Is it possible to reinit the interactive image? I need this for manipulations on the resize event.

**Comment by jpchateau** [comment]
Hi @theDyingMountain!
Thx you for your feedback, I appreciate!
I am not sure to understand the problem. After the windows is resized, you need the instance to be destroyed, the related HTML removed, events to be unbind and then create another instance to build all the items and effects?
Although I am sure it is possible to write this kind of destroy function, maybe all this is related to responsive design? The next iteration should be responsive, maybe this will solve the issue you are facing?
Or do you think a destroy function is really useful for other purposes?

**Comment by theDyingMountain** [comment]
Yes, I need a new instance to calculate new positions for the items. I wrote a function that calculates the position dynamically depended on the display resolution. This works for every page load, but for resize I need a destroy or reinit function. That is the only reason I think of. At the moment I don't find any other purposes.

**Comment by jpchateau** [comment]
Well, do you want to write this destroy/reinit function and submit a PR? I think you know the subject and I could focus on few other changes for a new version.

**Comment by jpchateau** [comment]
I did a few changes on the dev branch that could allow unbinding of all events on an instance and to create it again.

`
// Unbind all events
$('#my-interactive-image').unbind();

// Do your own stuff (resizing image, updating positions values of icons)
...

// Create a new instance
$("#my-interactive-image").interactiveImage(items, options);
`

I think it will do the job until the library adapts to all screen sizes.

**Comment by theDyingMountain** [comment]
Thx for implementing this. I will close the Issue now.
