### ISSUE TITLE
Error when share box is hidden.

### ISSUE THREAD

**Issue by Relin** [jpchateau/Interactive-Image#8]
Hi,
I encounter an error when the mouse leave the node.
After looking the code, I expect it's due to:
`src/js/event/behavior.js`
``` javascript
         this.$image.on('mouseleave', function() {
            const $elements = $(this).find('.hotspot, .item');
            $.each($elements, function() {
                DomHelper.hideElement($(this)[0]);
            });

            const $shareBox = $(this).find('.social-share-box');
            DomHelper.hideElement($shareBox[0]);
        });
```
Especially this line `DomHelper.hideElement($shareBox[0]);` where `$shareBox` can be empty if we use the option to hide the sharing box.

**Comment by jpchateau** [comment]
Hi @Relin !

I just released a fix for this issue. Check for version 2.7.1.
Thank you for having reported this issue and for bringing help to solve it!
