### ISSUE TITLE
Run function after everything is done

### ISSUE THREAD

**Issue by iamjackg** [jpchateau/Interactive-Image#9]
Hey there!

I'm a bit of a JS noob, and I'm trying to run a function to dynamically adjust the position of any tooltips that might appear off-screen. I'm having trouble figuring out _when_ I can run the function.

This does not seem to work, as the printed offset for all the items is the same (the origin of the containing div).

```js
$.when($("#main-map").interactiveImage(data, {
    shareBox: false,
    debug: false
})).then(function (result) {
    result.find(".item").each(function (item_index) {
        $(this).show();
        console.log($(this).offset());
    });
});
```

Could I get a pointer in the right direction? :)

Thanks!

**Comment by jpchateau** [comment]
Hello @iamjackg,
Sorry for the delay!
I created this code pen to help solving this issue: https://codepen.io/jpchateau/pen/qBZwQqw

First of all, I think I see the correct offset of each item (using FF).

Not sure about that, but you could try something like this in the function you execute for each item:

```
// Identify the items that are off screen
$('#main-map').off();
// Modify the data array of items with corrected positions
$("#main-map").interactiveImage(items, options);
```

Actually, it consists of detroying an instance and recreating it.
Tell me if it works!

**Comment by iamjackg** [comment]
Hey there!

Thanks for the suggestion. I'll look into it! The main issue I was running into was that I needed to wait while all the initialization happened asynchronously. I solved that by modifying the source to trigger a jQuery event when everything is done.

**Comment by jpchateau** [comment]
Thank you for the feedback. I close the issue.
